Update README.md
bmstu-iu9/utp2020-9-2d-game pull request #1
Opened 2020-07-08 22:49 UTC by MiNombreEsPetros

Добавил участников, их аккаунты в github и тему.

2020-07-09 07:42 UTC, Mazdaywik commented on index.html
> +	</head>
Отформатировано криво, по-видимому, перепутаны пробелы и табуляции.

2020-07-09 07:43 UTC, Mazdaywik requested changes
Поправьте, пожалуйста, форматирование в `index.html`.

2020-07-09 07:53 UTC, Mazdaywik commented
Для отступов нужно использовать либо только пробелы, либо только табуляции. В обоих случаях код будет отображаться более-менее приемлемо в любом текстовом редакторе с любыми настройками. Если их смешивать: в одних строчках табуляции, а в соседних пробелы — получится фигня.

Есть более сложный вариант — использовать табуляции для отступов, а пробелы для выравнивания:
https://habr.com/ru/post/118208/
но это немного сложнее.

Я предпочитаю использовать пробелы, но не навязываю, т.к. рискую начать холивар.

2020-07-09 07:56 UTC, Mazdaywik commented
Кстати, палитесь с тем, что клали файлы через web-интерфейс 😉. Осваивайте консольный гит! Он гораздо продуктивнее.

Либо некоторые среды разработки прекрасно интегрируются с Git, например, IntelliJ IDEA (Web Storm).

2020-07-10 14:55 UTC, MiNombreEsPetros commented
Хорошо! Постараюсь освоить,

2020-07-10 16:30 UTC, closed without merging